spring:
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    root: info

server:
  port: 5000

mixster:
  base-url: http://localhost:3000
  spotify:
    clientId: ${SPOTIFY_CLIENT_ID}
    clientSecret: ${SPOTIFY_CLIENT_SECRET}
    redirectUri: ${mixster.base-url}/spotify
    cookieName: spotify_token
