spring:
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    root: info

server:
  port: 8080

mixster:
  spotify:
    clientId: ${SPOTIFY_CLIENT_ID}
    clientSecret: ${SPOTIFY_CLIENT_SECRET}
    redirectUri: ${SPOTIFY_REDIRECT_URI:http://localhost:3000/spotify}
    cookieName: spotify_token
